name: Update Discord Icon

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:       # manual trigger button in GitHub UI

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: astral-sh/setup-uv@v6

      - run: uv run update_icon.py
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          GUILD_ID: ${{ secrets.GUILD_ID }}
          CITY: ${{ secrets.CITY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}